KRS\MailBundle\Entity\MailTemplate:
  type: entity
  table: karis_mail_template
  id:
    id:
      type: integer
      generator: { strategy: auto }
  fields:
    name:
      type: string(255)
      unique: true 
    description:
       type: text
       nullable: true
    vars_mail:
       type: text 
       nullable: true
    subject:
       type: text
    body:
      type: text
      nullable: true
    from_email:
      type: string(3000)
      nullable: true 
    to_email:
      type: string(3000) 
      nullable: true
    cc_email:
      type: string(3000) 
      nullable: true
    bcc_email:
      type: string(3000) 
      nullable: true
    reply_to_email:
      type: string(3000) 
      nullable: true
    sender_email:
      type: string(3000) 
      nullable: true
    list_unsuscribe:
      type: string(3000) 
      nullable: true
    template_file:
      type: string
      nullable: true  
    is_html:
      type: boolean
      nullable: true
      default: false 
    is_active:
      type: boolean
      nullable: true
      default: true 
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update   
  oneToMany:
    sentMail:
      targetEntity: SentMail
      mappedBy: mailTemplate