parameters:
    krs.mail_template.admin.class: KRS\MailBundle\Admin\MailTemplateAdmin
    krs.mail_template.entity:  KRS\MailBundle\Entity\MailTemplate
    krs.mail_template.controller: KRSMailBundle:MailTemplateAdmin
    
    krs.sent_mail.admin.class: KRS\MailBundle\Admin\SentMailAdmin
    krs.sent_mail.admin.entity:  KRS\MailBundle\Entity\SentMail
    krs.sent_mail.admin.controller: KRSMailBundle:SentMailAdmin
    
services:
     krs.mail_template.admin:
       class: "%krs.mail_template.admin.class%"
       tags:
        - { name: sonata.admin, manager_type: orm, group: sonata_manage_mail, label: Manage Mail Content }
       arguments: [null, "%krs.mail_template.entity%", "%krs.mail_template.controller%"]
       
     krs.sent_mail.admin:
       class: "%krs.sent_mail.admin.class%"
       tags:
        - { name: sonata.admin, manager_type: orm, group: sonata_manage_mail, label: Manage Mail sent }
       arguments: [null,"%krs.sent_mail.admin.entity%", "%krs.sent_mail.admin.controller%"]